version: '3.3'
services:
    web:
        build:
            context: ./html
            dockerfile: Dockerfile
        container_name: php73
        depends_on:
            - db
        volumes:
            - ./html:/var/www/html
        ports:
            - 8888:80
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    db:
        container_name: mysql8
        image: mysql:8.0
        volumes:
            - ./db:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: david
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - 3306:3306